### ISSUE TITLE
UEFI 32-bit CSMWrap

### ISSUE THREAD

**Issue by Gelip** [FlyGoat/csmwrap#10]
Please compile also UEFI 32-bit CSMWrap. I have Asus T100TAF (UEFI32 bios no CSM)
At the moment it is bricked but if I can fix it, I will gladly check if CSMWrap works.

P.S. Today test CSMWrap 64-bit on virt-manager OVMF pure-efi and on real machines (CSM disabled in CMOS):
https://msfn.org/board/topic/186793-csmwrap-boot-csm-on-uefi-only-systems/#findComment-1280095
https://msfn.org/board/topic/186793-csmwrap-boot-csm-on-uefi-only-systems/#findComment-1280103
Win10 ok in virt-manager
WinXP 32-bit ok in real machine but need Longhorn 5472 loader
WinXP 64-bit ok in real machine - boot on standard ntldr+NTDETECT.COM

**Comment by FlyGoat** [comment]
Thanks, it's not as easy as making a IA32 build but I also need to fix a good deal of stuff.

Will try tho.

**Comment by xCuri0** [comment]
The Apple TV port is 32-bit btw, seems like it needed a few changes to asm

**Comment by FlyGoat** [comment]
> The Apple TV port is 32-bit btw, seems like it needed a few changes to asm

Yes I can copy this part from EDK2 directly.
However it seems like there are a couple of data structure mismatch causing Hard Fault on my IA32  OVMF testing environment and I'll need to investigate further.

**Comment by FlyGoat** [comment]
Hi @Gelip, the latest IA32 build is working with QEMU OVMF IA32.

Can you try `csmwrapia32.efi` build in artifact of https://github.com/FlyGoat/csmwrap/actions/runs/15095522854?

**Comment by Gelip** [comment]
@FlyGoat 
Very Thx 👍 - I will check in virt-manager.
P.S. I need fix bricked Asus T100TAF (UEFI 32-bit) - Here https://www.elektroda.pl/rtvforum/topic4120094.html I described how I bricked it and tried to fix, but it seems that without de-soldering and programming the SPI with an external programmer, there is no way around it.

**Comment by mintsuki** [comment]
@FlyGoat hey, just wanted to point out that the GHA yml file that's supposed to publish the `ia32`/`x64` artifacts actually has a bug and it only publishes 1 file. Basically:
```yaml
    - uses: actions/upload-artifact@v4
      with:
        name: csmwrap.efi
        path: bin/*.efi
```
Should be something like:
```yaml
    - uses: actions/upload-artifact@v4
      with:
        name: csmwrapx64.efi
        path: bin/csmwrapx64.efi
    - uses: actions/upload-artifact@v4
      with:
        name: csmwrapia32.efi
        path: bin/csmwrapia32.efi
```
Similar to what you have already done for the release portion.
